### ISSUE TITLE
Publish example does not work

### ISSUE THREAD

**Issue by elwayman02** [lytics/ember-cli-release#25]
I tried the following config:

```js
/* jshint node:true */
var RSVP = require('rsvp');
var publisher = require('publish');

// Create promise friendly versions of the methods we want to use
var start = RSVP.denodeify(publisher.start);
var publish = RSVP.denodeify(publisher.publish);

module.exports = {
  manifest: ['package.json'],

  // Publish the new release to NPM after a successful push
  // If run from travis, this will look for the NPM_USERNAME, NPM_PASSWORD and
  // NPM_EMAIL environment variables to publish the package as
  afterPush: function() {
    return start().then(function() {
      return publish({});
    });
  }
};
```

...with publish added as an npm devDependency for the project.

Unfortunately, it does not seem to get triggered, and I've had to publish manually.

**Comment by slindberg** [comment]
- What version are you using? The `afterPush` hook was added in [v0.2.4](https://github.com/lytics/ember-cli-release/blob/master/CHANGELOG.md#v024-july-5-2015).
- Have you done a [`npm adduser`](https://docs.npmjs.com/cli/adduser)?
- I assume you also added `rsvp` as a dev dependency
- Are you seeing any errors? Any output at all that is NPM related?
- I'm using this example in [`ember-data-model-fragments`](https://github.com/lytics/ember-data.model-fragments/blob/master/config/release.js)

**Comment by rwjblue** [comment]
I know it is cheating, but assuming you run Node 0.12+ or iojs you can just `execSync` `npm publish`.

I use the following in quite a few projects:

```javascript
var execSync = require('child_process').execSync;

module.exports = {
  // Publish the new release to NPM after a successful push
  afterPush: function() {
    console.log('publishing to npm');
    var output = execSync('npm publish', { encoding: 'utf8' });
    console.log(output);
  }
};
```

**Comment by elwayman02** [comment]
@slindberg I'm using ember-cli-release 0.2.3, which is what got automatically installed thanks to the addon blueprint :(

All the more reason for https://github.com/ember-cli/ember-cli/pull/4891, I suppose.
