### ISSUE TITLE
Add `preventRelease` hook.

### ISSUE THREAD

**Issue by rwjblue** [lytics/ember-cli-release#30]
There have been a number of times that I have wanted a hook in `config/release.js` that is called with the same arguments as `beforeCommit` and `afterPush` which allows me to prevent any modifications.  This would be done just after [step 3](https://github.com/lytics/ember-cli-release#workflow).

A few scenarios where this would be helpful:

* Ensuring that local `master` is up to date with remote `master`. If this is not true, the `git push origin master` step fails, but only after already commiting and tagging locally.  We should probably detect this scenario all the time (and not rely on a new hook), but it is a good example of why a hook would be useful.
* Ensuring that the local system is setup for `afterPush` process.  Assume that you need to run a series of commands in `afterPush`, and you want to avoid commiting/tagging/pushing if the local system isn't properly setup. [Example](https://github.com/rwjblue/ember-qunit/blob/master/config/release.js)

My thought was that if we added a `preventRelease` hook you could return `true` to prevent modifications. Something like:

```javascript
module.exports = {
  preventRelease: function(project, versions) {
    // do something here to detect stuff
    if (tharBeDragons) {
      return true;
    }
  }
};
```

I am not very tied to the name `preventRelease` (open to better suggestions).

**Comment by slindberg** [comment]
It seems to me like we're just missing a hook that runs after the tag is calculated but before anything filesystem changes. I'm in favor of creating a new hook whose name is descriptive of when in the workflow it runs; `preventRelease` implies to me that it is executed before pushing things, not before anything really happens.

Throwing from a hook already aborts the release and prints the error message (although maybe it could be wrapped in `SilentError` for better formatting). If the name doesn't imply that its sole purpose is for aborting, throwing an error is a natural way to prevent anything else from happening.

What about `beforeReplace`? I'm also having trouble coming up with a decent name.
