### ISSUE TITLE
Introduction to ember-cli-release at Global Ember Meetup

### ISSUE THREAD

**Issue by taras** [lytics/ember-cli-release#34]
Hi there, would you someone familiar with the project would be open to giving an "Introduction to ember-cli-release" lightning talk at an upcoming Global Ember Meetup in the beginning of next year? We'll edit the video and give you video that you can embed into the addon's README. You can see an example of other introduction videos here https://vimeo.com/album/3607049

The talk usually covers:
1. What's use case for the addon?
2. How to get stated using it?
3. What should the user be aware of?

What do you think?

**Comment by slindberg** [comment]
I could maybe swing that. Hit me up on the Ember community slack to discuss details.

**Comment by taras** [comment]
Sent you a message, but would you be able to make January 16th or January 30th?
