### ISSUE TITLE
Error while installing v1.0.0-beta.1

### ISSUE THREAD

**Issue by seawatts** [lytics/ember-cli-release#49]
I am getting an error when I try to install the latest beta
```
npm ERR! enoent ENOENT: no such file or directory, chmod './my-repo/node_modules/ember-cli-release/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js'
```

**Comment by karellm** [comment]
I'm having the same issue. I think it is related to npm 3. See [here](https://github.com/npm/npm/issues/9517). Personally running `node@5.4.0` and `npm@3.3.12`.

**Comment by rwjblue** [comment]
npm 3.3.10 through 3.3.12 are completely hosed, update npm to 3.4.1 or later

**Comment by rwjblue** [comment]
See https://github.com/lytics/ember-cli-release/issues/46

**Comment by rwjblue** [comment]
See upstream issue: https://github.com/npm/npm/issues/10458

**Comment by karellm** [comment]
I confirm that it fixed the issue for me. For future reference, upgrade npm: `npm install -g npm@^3`

**Comment by slindberg** [comment]
Thanks for fielding these @rwjblue, I would have been completely lost. Sounds like this is resolved, closing.
