### ISSUE TITLE
Remove ember deprecation warning and release as 0.2.9

### ISSUE THREAD

**Issue by Serabe** [lytics/ember-cli-release#55]
Can you please apply #53 on top of version 0.2.8 and release as 0.2.9, please?

The fix is only in a 1.0.0 beta and users are complaining about a deprecation warning being there :(.

Ember-cli pins version to 0.2.9 but I can send a PR as soon as this is released.

Thank you!

**Comment by rwjblue** [comment]
I pushed https://github.com/lytics/ember-cli-release/tree/stable-0-2-x with the fix from #53.  It is ready for releasing 0.2.9 from that branch, but I can't push to NPM.

@slindberg - If you have a minute, would you mind pushing a 0.2.9 from that branch?

**Comment by slindberg** [comment]
Released & published.

@rwjblue, I added you as a collaborator on NPM yesterday, did you attempt to publish and it failed?

**Comment by Serabe** [comment]
Thank you both!

**Comment by rwjblue** [comment]
@slindberg - I didn't try, but I did run 'npm owners ls ember-cli-release' and didn't think it showed me, but I could be wrong. 

Thanks again for publishing!

**Comment by slindberg** [comment]
@rwjblue I don't know what the difference between a contributor and owner is, but you are an owner now too 😉
