### ISSUE TITLE
"Skipped tagging, HEAD already at tag: v0.1.0"

### ISSUE THREAD

**Issue by tsteuwer** [lytics/ember-cli-release#59]
So I just tried using ``ember release --minor`` and everything worked as expected for my first try. It set the package.json to version 0.1.0. I just tried doing another minor release using the same ``ember release --minor`` and I'm getting the error:

```
troy@troy-XPS-8300:~/development/bk-core-services$ ember release --minor
Skipped tagging, HEAD already at tag: v0.1.0
```

Shouldn't it bump it to v0.1.1? What am I doing wrong?

**Comment by tsteuwer** [comment]
This has nothing to do with this addon. I guess it's part of ember-cli's.

**Comment by reidab** [comment]
I'm running into the same issue, and it certainly looks like the code in question in in this addon, not ember-cli: 

- https://github.com/lytics/ember-cli-release/blob/2d6fc5ee2421253a8c4345cc03b6092f0eec0290/lib/commands/release.js#L172-L178
- https://github.com/lytics/ember-cli-release/blob/2d6fc5ee2421253a8c4345cc03b6092f0eec0290/lib/commands/release.js#L371

Our CI system adds build tags to our git repo, so bailing out if there's already a tag on a given commit is really undesirable. Is there a reason that ember-cli-release should fail to work on already-tagged commits?
