### ISSUE TITLE
Using without ember-cli

### ISSUE THREAD

**Issue by knownasilya** [lytics/ember-cli-release#7]
This looks like a useful module even for non-ember-cli projects. Would be nice to pull out the core features into a regular npm module, with a bin (which could be used here, and this would be a lightweight wrapper).

**Comment by elwayman02** [comment]
@knownasilya https://github.com/semantic-release/semantic-release

**Comment by elwayman02** [comment]
@slindberg do you think there's any merit to leveraging semantic-release inside ember-cli-release instead of the implementation we have today? Seems like semantic-release has a ton of useful features.

**Comment by knownasilya** [comment]
Thanks @elwayman02

**Comment by oskarrough** [comment]
Semantic release is quite different as it relies on using keywords in commit messages. [Release It!](https://github.com/webpro/release-it) is more in line with how ember-cli-release currently works.

**Comment by slindberg** [comment]
Closing since there are other tools out there that do a similar job, and maintaining a separate package for core functionality is not exactly something I'm excited about doing.
