### ISSUE TITLE
Hook to update versions of additional files?

### ISSUE THREAD

**Issue by lukemelia** [lytics/ember-cli-release#8]
We're working on a cordova app that has has android and ios files with version numbers in addition to package.json and bower.json. Would you be open to a PR that allows apps to configure a hook that will be run by ember-cli-release when a new version number is being applied to manifest files?

**Comment by slindberg** [comment]
Yes! Hooks are great :+1:

Making the list of manifest files configurable has been on my TODO list for while, would that be sufficient for your purposes, or do you need to make custom edits to those files at the same time? BTW, I'm usually on ember slack and freenode if you'd like to DM me.

**Comment by rwjblue** [comment]
I would also love a hook (and to have the list of manifest files configurable).

**Comment by lukemelia** [comment]
@slindberg I think a hook is going to be more flexible because not all manifest files will be JSON with a `version` key.

**Comment by rwjblue** [comment]
Would it be feasible to have the hooks default implementation be the current JSON manifest 'version' bump? Or should they be kept separate?

**Comment by lukemelia** [comment]
I'm inclined to keep them separate.

I pushed an implementation. See #12

**Comment by slindberg** [comment]
Hooks released in [v0.2.4](https://github.com/lytics/ember-cli-release/tree/v0.2.4).
